# Generated by Django 4.1.5 on 2023-01-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgmobileshopapp', '0003_remove_category_image_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mrp', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('image', models.ImageField(upload_to='products_image')),
                ('description', models.TextField(max_length=200)),
                ('qty', models.IntegerField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmobileshopapp.brand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmobileshopapp.category')),
            ],
        ),
    ]
