# Generated by Django 4.1.5 on 2023-01-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgmobileshopapp', '0004_remove_brand_id_remove_category_id_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
